import os

DEFAULT_CLUSTERS = 4
DEFAULT_SEED = 27
CLUSTER_COLUMN = "Cluster"
DATASET_PATH = "./wlb_cities.csv"
STOP_EPSILON = 0.1
PROCESSORS = os.cpu_count()
AMOUNT_SEED_TESTS = 10
ITERATION_THRESHOLD = 1000
MAX_K_PLUS_1 = 30